#!/usr/bin/env python3

import termtosvg.main
import sys
import subprocess
import time


if __name__ == '__main__':
    proc = 0
    if ('window_frame_js_audio' in sys.argv):
        proc = subprocess.Popen(['ffmpeg'
            , '-nostdin'
            , '-hide_banner'
            , '-f'
            , 'avfoundation'
            , '-y'
            , '-i'
            , ':0'
            , '-f'
            , 'mp3'
            , 'hello.mp3'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    termtosvg.main.main()
    if (proc != 0):
       proc.terminate()
